export { default as RoleModel } from './role.model.js'
export { default as UserModel } from './user.model.js'
export { default as AdministrativosModel } from './administrativos.model.js'
export { default as EstudiantesModel } from './estudiantes.model.js'
export { default as AcademicosModel } from './academicos.model.js'
export { default as MateriasModel } from './materias.model.js'
